name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, @${{ github.actor }} welcome to this repository 🎊. Thank you so much for taking the time to point this out.🙌"
        pr-message: "Hey, @${{ github.actor }} welcome to this repository🎊 Thank you for taking your time and effort to make our project better, truly value it :tada: 🙌 ! Keep making such awesome contributions!"
